# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/seanj/Documents/Kent_0/Kent_0/Kent_0.srcs/sources_1/ip/program_memory/program_memory.xci
# IP: The module: 'program_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/seanj/Documents/Kent_0/Kent_0/Kent_0.srcs/sources_1/ip/program_memory/program_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/seanj/Documents/Kent_0/Kent_0/Kent_0.srcs/sources_1/ip/program_memory/program_memory.xci
# IP: The module: 'program_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/seanj/Documents/Kent_0/Kent_0/Kent_0.srcs/sources_1/ip/program_memory/program_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'program_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
